### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by nathanprocks** [Domination9987/KissAnime-Cartoon-Downloader#1]
Browser: Google Chrome version 48.0.2564.10 dev (64-bit)
OS: Mac OS X 10.11.1
(I'm not sure if this matters because a friend running the latest stable Chrome on Windows also has this issue.)

When trying to download on the KissAnime episode list page, it fails with errors that say:
>You have encountered an error. Please send details of this error to the developer at Greasyfork or GitHub.
>
>(iframeCheck): Something went wrong with: "Fairy Tail (Dub) 025 - A Flower Blooms in the Rain".
>
>It probably isn't redirecting properly. This could be because of slow internet or slow servers. Try increasing the 'Error Timeout' amount in the settings to fix this

In the JS console it says
>GET https://2.bp.blogspot.com/Pu6nZnOi0nTjSu27JALHI3lgV9mBWXR3SqWIMe8OhgA=m22 403 (OK)

I created an Iframe on the page and set the URL to the one in the error message. It seems like Google is blocking the requests.
>403 That’s an error.
>
>Your client does not have permission to get URL /Pu6nZnOi0nTjSu27JALHI3lgV9mBWXR3SqWIMe8OhgA=m22 from this server. (Client IP address: 101.178.135.193)
>
>Blacklisted Referrer That’s all we know.

I searched for ways to set the referer URL in JavaScript. None of the methods I found work anymore.

**Comment by Domination9987** [comment]
Yeah I think it has something to do with HTTPS and/or the new security policies that KAnime have implemented recently. It's really annoying because the links work from the browser in a new window but not in an iframe (might be due to the host or something?)

It seems to work from the episode page though. I'm going to try and use this to create an iframe chain:
Series page -> Episode page -> video

Which will then send the frame deletion request:
video -> Episode page -> Series page


This appears to work (just need to implement)

**Comment by Domination9987** [comment]
Fixed in 0.46 (probably).

Made it so that it always requests the videos from the episode page from another frame (frameception?)

Thanks for putting together detailed post above by the way, it's well formatted and is a good reference for this issue.

Let me know if it doesn't work on OSX :)

**Comment by nathanprocks** [comment]
I'm still having a similar issue. This time the videoplayback URL isn't blocked (206 response) but I am still getting the "iframeCheck" error. (Tested on Chrome and Firefox)

**Comment by Domination9987** [comment]
Does it if you download through browser (and without "allow insecure scripts" workaround?)

Try 0.47, it fixes problems relating to the URL of the frame (quotation characters ruined the passing of data, causing the script to crash) ~ This may be what was causing a 206 response

**Comment by nathanprocks** [comment]
Downloading through the browser still does not work in 0.47. I can't see any related errors in the console.  I still get a 206 response for the videoplayback, which seems to be normal as I get the same response when directly loading the video in new tab.

**Comment by Domination9987** [comment]
Is it one specific video or all videos?

**Comment by nathanprocks** [comment]
I checked a few different videos on KissAnime and it has only happened with the [Fairy Tail](https://kissanime.to/Anime/Fairy-Tail-Dub) series. On other videos, the iframeCheck error appears, then the download starts a few seconds after.

**Comment by Domination9987** [comment]
This was happening due to the naming scheme of the videos. In most anime, a video's title contains "Episode xxx" or "Movie" or "OVA", etc. The Fairy Tail series, however, is in the format "xxx - <ep name>". 

This meant that the script didn't recognise the episode pages as videos, resulting in the script never requesting the page to be downloaded.

Should hopefully work in 0.48

**Comment by nathanprocks** [comment]
Thank you. It functions properly now.

Closing.
